### ISSUE TITLE
Can't pickle some search results

### ISSUE THREAD

**Issue by plammens** [nachocho/pyrae#5]
Right now pickling is not generally possible due to reference cycles in the HTML soup (I don't know if this is something to do with the implementation of BeautifulSoup or if it is just the nature of the HTML itself which might contain cycles).  So if you try to pickle such a search result you get a RecursionError.

Example:

```python
import pickle
from pyrae import dle

search_result = dle.search_by_word("ver")
pickle.dumps(search_result, protocol=-1)
```
```none
RecursionError: maximum recursion depth exceeded while pickling an object
```

It would be good to implement a custom `__getstate__` and `__setstate__` or other means to allow pickling `pyrae` objects.

**Comment by nachocho** [comment]
Reviewing further the sample code you provided, do you need to pickle the actual SearchResult instance?
If you are pickling and unpickling, why not doing that with the dictionary representation instead of the actual SearchResult instance?

Maybe there is a valid reason for you to want to pickle the object instance, just can't imagine it now.
Pickling the dict works perfectly:

```
import pickle
from pyrae import dle

search_result = dle.search_by_word("ver")
pickle.dumps(search_result.to_dict(), protocol=-1)
```

I agree anyway that what you are reporting is an issue.

Thanks.

**Comment by nachocho** [comment]
This has been fixed on commit 7cda420.

**Comment by plammens** [comment]
Now that you mention it, converting to and from dictionaries for persisting/caching results to disk seems like a good idea since it bypasses the HTML parsing. I've seen the `to_dict` function you point out, but has the inverse operation been implemented currently? I haven't seen a `from_dict` or equivalent function

**Comment by nachocho** [comment]
> Now that you mention it, converting to and from dictionaries for persisting/caching results to disk seems like a good idea since it bypasses the HTML parsing. I've seen the `to_dict` function you point out, but has the inverse operation been implemented currently? I haven't seen a `from_dict` or equivalent function

No, there is no `from_dict` function implemented, and actually I don't see the benefit of adding one or the use case. The SearchResult object is now pickable, so if you need to persist or cache a search result you can do that as well if the cache is not good for your needs.

**Comment by plammens** [comment]
It is mainly a performance thing — parsing the HTML seems to take up quite a bit of time:

![image](https://user-images.githubusercontent.com/18049056/124160042-bb28e800-da93-11eb-804f-0876f9da359b.png)
(This is part of the call graph from a profiling result from a project I'm working on.)

So I'm trying to see whether there is any way to bypass that, i.e. reconstruct the object straight from the parsed attributes.

In any case, hanks for your help!

**Comment by nachocho** [comment]
What I mean is, the intention of the library is to perform searches against the RAE, and that of course involves scraping the HTML page of the search result from the RAE website.  I do not understand what you are trying to do to reconstruct a SearchResult object from a dict, it would normally not be needed to perform searches and in my head it does not make sense for the purposes of the library.

All of the objects are now pickable, meaning they can be cached if needed. I still fail to see (after seeing the profiling graph you provided) the use case of taking a dictionary and reconstruct the objects used to perform a search against the RAE from the dictionary.

You can subclass the classes used to perform the search and implement a from_dict if you have a very particular need.
