### ISSUE TITLE
Fixing Non-personal form of the verb

### ISSUE THREAD

**Issue by Cxx-mlr** [nachocho/pyrae#9]
`Conjugation(FromHtml)._parse_html` doesn't properly extract the Non-personal form of the verb: Infinitivo, Gerundio and Participio

doesn't work

https://github.com/nachocho/pyrae/blob/4b4aaabf160ef91294a27767f99d67bb863ce4e4/pyrae/core.py#L988

```json
"conjugations": {
    "Formas no personales": {
        "Infinitivo": "",
        "Gerundio": "",
        "Participio": "",
        "": "amado"
    },
}
```

this works:

```python
if re.search(pattern=f'/ {key}' if key not in ['Presente', 'Infinitivo', 'Gerundio', 'Participio'] else key,
```

```json
"conjugations": {
    "Formas no personales": {
        "Infinitivo": "amar",
        "Gerundio": "amando",
        "Participio": "amado"
    },
}
```

**Comment by nachocho** [comment]
Thanks for raising this issue and for the suggestion, I will implement this in a chance and make sure the unit tests that I have in the roadmap cover this scenario.

**Comment by nachocho** [comment]
This is now fixed in base code.
Thanks a lot for raising the issue and giving me the fix for it, and sorry for the late response, I work on this and other projects in my free time which is not much lately.
